version: "3"                                                                                                                                                           services:
mysqldb:                                                                                                                                                                  
 container_name: mysqldb
 image: mysql:latest
 environment:                                                                                     
  MYSQL_ROOT_PASSWORD: root                                                                                                                                               
  MYSQL_DATABASE: mysqldb                                                                                                                                            
 volumes:                                                                                                                                                                  
  - mysql_data:/var/lib/mysql                                                                                                                                            
  - ./mysql/my.cnf:/etc/mysql/my.cnf   

spring-app:
  image: medalibm/achat:latest
  ports:
   - 5100:8089
  depends_on:
   - mysqldb
  environment:
   MYSQL_HOST: mysqldb
   SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/achatdb
useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
   SPRING_DATASOURCE_USERNAME: root
   SPRING_DATASOURCE_PASSWORD:
                                                                                                                             
volumes :
mysql_data:
